export {
  hashPassword,
  verifyPassword,
  createToken,
  verifyToken,
  setAuthCookie,
  removeAuthCookie,
  getAuthToken,
  getCurrentUser,
  requireAuth,
  requireAdmin,
  updateStreak,
  addXp,
  calculateLevel,
  xpForLevel,
  xpToNextLevel,
} from './auth';
